steps:
  - label: ":docker: Build Project"
    plugins:
      - docker#v3.9.0:
          image: "golang:1.18.0"
          workdir: "/app"
          volumes:
            - ".:/app"
    command:
      - go build -o hello/hello ./hello
    artifact_paths:
      - "hello/hello"
  - label: ":pause_button: Enter Name"
steps:
  - label: ":snyk: Test Go"
    command:
      - go mod download
      - snyk test
    plugins:
      - docker#v5.9.0:
          image: "snyk/snyk:golang"
          workdir: "/project"
          volumes:
            - ".:/project"
          environment:
            - SNYK_TOKEN
    type: block
    prompt: "Please enter your name"
    fields:
      - text: "Your name"
        key: "user_name"
        hint: "Enter your name here"
  - label: ":running: Run Program with Name"
    command:
      - buildkite-agent artifact download "hello/hello" .
      - chmod +x hello/hello
      - ./hello/hello $(buildkite-agent meta-data get "user_name")
  - label: ":eyes: Manual Approval"
    type: block
    prompt: "Approve to continue to the final step"
